### ISSUE TITLE
Gutenberg error when opening style selection

### ISSUE THREAD

**Issue by strarsis** [ArrayHQ/atomic-blocks#67]
When opening the style selection (accordion in sidebar) for the AB Container block,
Gutenberg editor crashes and displays an error popup. Error message:
````
TypeError: Cannot read property 'innerBlocks' of null
    at t.value ([...]/app/plugins/gutenberg/build/editor/index.js?ver=1550716684:50:144165)
    at commitLifeCycles ([...]/app/plugins/gutenberg/vendor/react-dom.60482cc7.js:16085:22)
    at commitAllLifeCycles ([...]/app/plugins/gutenberg/vendor/react-dom.60482cc7.js:17386:7)
    at HTMLUnknownElement.callCallback ([...]/app/plugins/gutenberg/vendor/react-dom.60482cc7.js:143:14)
    at Object.invokeGuardedCallbackDev ([...]/app/plugins/gutenberg/vendor/react-dom.60482cc7.js:193:16)
    at invokeGuardedCallback ([...]/app/plugins/gutenberg/vendor/react-dom.60482cc7.js:250:31)
    at commitRoot ([...]/app/plugins/gutenberg/vendor/react-dom.60482cc7.js:17582:7)
    at completeRoot ([...]/app/plugins/gutenberg/vendor/react-dom.60482cc7.js:19036:3)
    at performWorkOnRoot ([...]/app/plugins/gutenberg/vendor/react-dom.60482cc7.js:18965:9)
    at performWork ([...]/app/plugins/gutenberg/vendor/react-dom.60482cc7.js:18873:7)
````

Two styles have been added to the AB Container block by theme (Border and Empty):
```js
wp.domReady( () => {

  wp.blocks.registerBlockStyle( 'atomic-blocks/ab-container', {
    name: 'border',
    label: 'Border',
    isDefault: true,
  } );

  wp.blocks.registerBlockStyle( 'atomic-blocks/ab-container', {
    name: 'empty',
    label: 'Empty',
  } );

} );
````

**Comment by mikemcalister** [comment]
Hi there, 

I'm not having any issues with the AB container block itself. It seems like this is due to your addition to the block via the theme. Unfortunately, we can't troubleshoot your block additions at this time, but feel free to send over more info if you come across it.

**Comment by mikemcalister** [comment]
Keep an eye on [this ticket](https://github.com/WordPress/gutenberg/issues/9897), as it outlines the Gutenberg core bug and its progress.
